### ISSUE TITLE
Build on Linux with Qt5 libraries

### ISSUE THREAD

**Issue by agguro** [ho229v3666/QtDemos#4]
Before building it on Linux with Qt5 you need to install:
sudo apt install libsdl2-dev libavfilter-dev

**Comment by ho-229** [comment]
Hi, I haven't used Debian for a long time, so I gave wrong suggestions.
Thanks for your suggestion.

**Comment by ho-229** [comment]
done.
https://github.com/ho229v3666/QtDemos/commit/b7d6160d41f8945b21d022160a79570ab8a25dbd
